### ISSUE TITLE
Brainstorm Recipes

### ISSUE THREAD

**Issue by ominestre** [ominestre/nanite#4]
We need to determine the best way to allow a user of our composer to create and use their own recipes.

I'm thinking about something beyond just a config file here. It would be nice if we supported extensions where users could create templates of their own.

**Comment by ominestre** [comment]
First thing I can think of for the structure of a recipe is:

| - nanite-config.yml
|
| - templates/
| --- | - my-template-file.hbs
| --- | - my-template-file-two.hbs
|
| - models/
| --- | - template-data-model.js

The main config would define project structure and variations. Template directory would be flat and it would be up to the config to determine where the generated output would go. Models is a way to variations of the data injected into your templates should there be multiple versions of your recipe.

This is extremely POC but I'm thinking this would work like `nanite --recipe foo` and if there are variants we will prompt the user to choose. Or we could also do something like `nanite --recipe foo --variant bar` as well.

How the config file looks will be determined.

**Comment by ominestre** [comment]
```yaml
project-layout:
  some-directory:
    some-file.js:
      template: 'some-file.hbs'
      model: 'some-file.model.js'
    another-file.json:
      template: 'another-file.hbs'
      data:
        foo: 'foo'
        bar: 'not foo'
  package.json:
    template: 'package.hbs'
    date:
      project-name: 'my project'
      version: '300.3.14.135135867183rc'
```

First brainstorm on how the config file for generating the structure could look. I'm going to run a lab on this since I'm not even sure if that's valid yaml having the extensions in the prop names. Might have to move those into an `ext` property of the object instead.
